import {StyleSheet} from 'react-native';
import {Colors, rgba} from '../../Theme/Colors';
import {hp, rfs, wp} from '../../Theme/Responsiveness';
import Typography from '../../Theme/Typography';

export const styles = StyleSheet.create({
  mainView: {
    backgroundColor: 'white',
    flex: 1,
  },
  subContainer: {
    paddingHorizontal: wp(3),
  },
  vehicleTabContainer: {
    paddingHorizontal: wp(3),
    marginBottom: hp(3),
  },
  content: {
    paddingHorizontal: wp(3),
    paddingBottom: hp(5),
  },
  flatlistContent: {
    paddingHorizontal: wp(3),
    paddingBottom: hp(50),
  },
  timelineContent: {
    paddingHorizontal: wp(3),
    paddingBottom: hp(5),
  },
  rowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  vehicleUpperRowContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginVertical: hp(1),
  },
  pointMainContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(2.3),
  },
  profileIconsContainer: {
    flexDirection: 'row',
    marginTop: hp(1.5),
    alignItems: 'center',
  },
  row: {
    flexDirection: 'row',
  },
  carPropContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(1),
    flexWrap: 'wrap'
  },
  carPropsContainer: {
    backgroundColor: rgba(Colors.white, 0.12),
    borderRadius: wp(2),
    paddingHorizontal: wp(3),
    paddingBottom: hp(1),
  },
  priceTxt: {
    color: 'white',
    fontSize: wp(3.5),
    fontFamily: Typography?.poppins?.Regular,
  },
  carName: {
    color: Colors.black,
    maxWidth: wp(40),
    fontSize: wp(3.7),
    fontFamily: Typography?.poppins?.SemiBold,
  },
  whiteProfileName: {
    color: 'white',
    fontSize: wp(3.7),
    fontFamily: Typography?.poppins?.SemiBold,
    marginTop: hp(1),
  },
  optionName: {
    color: Colors.black,
    fontSize: wp(3.5),
    fontFamily: Typography?.poppins?.Regular,
    width: wp(30),
  },
  itemOptionName: {
    color: Colors.black,
    fontSize: wp(3.5),
    fontFamily: Typography?.poppins?.Regular,
    width: wp(20),
  },
  itemContainer: {
    backgroundColor: Colors.dullWhite,
    paddingHorizontal: wp(2),
    paddingVertical: hp(1.2),
    borderRadius: wp(3),
    marginBottom: hp(2),
  },
  greyContainer: {
    backgroundColor: Colors.dullWhite,
    paddingHorizontal: wp(2),
    paddingVertical: hp(1.5),
    borderRadius: wp(3),
    marginVertical: hp(2),
  },
  screenTabContainer: {
    backgroundColor: Colors.dullWhite,
    paddingHorizontal: wp(4),
    paddingVertical: hp(0.9),
    borderRadius: wp(1.6),
    marginRight: wp(3),
  },
  modalContainer: {
    backgroundColor: 'white',
    paddingHorizontal: wp(5),
    paddingVertical: hp(2),
    borderRadius: wp(3),
  },
  rowSpaceContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  vehicleHeadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: hp(1),
  },
  headingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(2)
  },
  itemOptionSpaceContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 1,
  },
  tabContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  optionSpaceContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: hp(0.5),
  },
  plusOptionContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    backgroundColor: Colors.dullWhite,
    borderRadius: wp(2),
    paddingVertical: hp(1),
    paddingHorizontal: wp(3),
    marginBottom: hp(0.5),
  },
  searchContainer: {
    marginTop: hp(2.5),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  centerSpaceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  subHeaderContainer: {
    marginVertical: hp(1.4),
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  iconStyle: {
    width: wp(12),
    height: hp(6),
  },
  backIcn: {
    width: wp(4),
    height: hp(2),
  },
  profileImg: {
    width: wp(24),
    height: hp(12),
  },
  listForwardIcn: {
    width: wp(3),
    height: hp(1.5),
    marginLeft: wp(1),
  },
  crossIcn: {
    width: wp(5.5),
    height: hp(2.75),
  },
  optionIcn: {
    width: wp(5.5),
    height: hp(3),
    marginTop: hp(0.2),
  },
  tabIcn: {
    width: wp(4.5),
    height: hp(2.25),
  },
  priceContainer: {
    backgroundColor: Colors.primary,
    paddingHorizontal: wp(4),
    paddingVertical: hp(0.65),
    borderRadius: wp(5),
  },
  primaryPriceContainer: {
    backgroundColor: Colors.primary,
    paddingHorizontal: wp(4),
    paddingVertical: hp(0.65),
    borderRadius: wp(5),
  },
  profileContainer: {
    marginLeft: hp(1.5),
  },
  description: {
    color: Colors.greyIcn,
    width: wp(55),
    flexDirection: 'row',
    flexWrap: 'wrap',
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.1),
  },
  descriptionPlaceholder: {
    color: Colors.greyIcn,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3),
    width: wp(80),
    marginTop: hp(1.5),
  },
  subTitle: {
    color: Colors.greyIcn,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3),
    marginTop: hp(0.5),
  },
  whiteDescription: {
    color: rgba(Colors.white, 0.6),
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.1),
    marginTop: hp(0.4),
  },
  detailText: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.3),
  },
  viewText: {
    color: Colors.primary,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(3.3),
    alignSelf: 'center',
  },
  task: {
    color: Colors.shadeGreen,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(4),
  },
  note: {
    color: Colors.shadeBlue,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(4),
  },
  taskContainer: {
    backgroundColor: rgba(Colors.shadeGreen, 0.2),
    paddingHorizontal: wp(5),
    borderRadius: wp(2),
    paddingVertical: hp(0.4),
  },
  noteContainer: {
    backgroundColor: rgba(Colors.shadeBlue, 0.2),
    paddingHorizontal: wp(5),
    borderRadius: wp(2),
    paddingVertical: hp(0.4),
  },
  document: {
    color: Colors.shadeOrange,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(4),
  },
  documentContainer: {
    backgroundColor: rgba(Colors.shadeOrange, 0.2),
    paddingHorizontal: wp(5),
    borderRadius: wp(2),
    paddingVertical: hp(0.4),
  },
  sms: {
    color: Colors.shadeDullBlue,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(4),
  },
  smsContainer: {
    backgroundColor: rgba(Colors.shadeDullBlue, 0.2),
    paddingHorizontal: wp(5),
    borderRadius: wp(2),
    paddingVertical: hp(0.4),
  },
  appointment: {
    color: Colors.shadeLightBlue,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(4),
  },
  appointmentContainer: {
    backgroundColor: rgba(Colors.shadeLightBlue, 0.2),
    paddingHorizontal: wp(5),
    borderRadius: wp(2),
    paddingVertical: hp(0.4),
  },
  email: {
    color: Colors.shadeRed,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(4),
  },
  emailContainer: {
    backgroundColor: rgba(Colors.shadeRed, 0.2),
    paddingHorizontal: wp(5),
    borderRadius: wp(2),
    paddingVertical: hp(0.4),
  },
  vehicle: {
    color: Colors.shadeGrey,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(4),
  },
  vehicleContainer: {
    backgroundColor: rgba(Colors.shadeGrey, 0.2),
    paddingHorizontal: wp(5),
    borderRadius: wp(2),
    paddingVertical: hp(0.4),
  },
  pointContainer: {
    backgroundColor: rgba(Colors.darkGrey, 0.5),
    borderRadius: wp(10),
    paddingHorizontal: wp(3),
    paddingVertical: hp(1),
    marginRight: wp(3),
  },
  pointText: {
    color: Colors.greyIcn,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.3),
  },
  whiteDetailText: {
    color: 'white',
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.5),
  },
  detailContainer: {
    marginTop: hp(0.5),
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  crossContainer: {position: 'absolute', top: hp(1), right: wp(2)},
  optionText: {
    color: Colors.greyIcn,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3),
    marginRight: wp(1.5),
    marginTop: hp(0.4),
  },
  carOptionText: {
    color: Colors.white,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3),
    marginRight: wp(1.5),
    marginTop: hp(0.4),
  },
  carValueText: {
    color: Colors.white,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(3),
  },
  valueText: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(3),
  },
  descriptionText: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(3),
  },
  optionContainer: {
    position: 'absolute',
    zIndex: 1000,
    backgroundColor: 'white',
    paddingHorizontal: wp(2),
    paddingVertical: hp(1),
    borderRadius: wp(2),
    top: hp(3),
    right: wp(3),
  },
  header: {backgroundColor: Colors.primary, paddingBottom: hp(2)},
  placeholderText: {
    color: Colors.primary,
    fontSize: wp(3.5),
    fontFamily: Typography?.poppins?.Medium,
    marginBottom: hp(0.5),
  },
  blackPlaceholderText: {
    color: Colors.black,
    fontSize: wp(3.5),
    fontFamily: Typography?.poppins?.Regular,
    marginBottom: hp(0.5),
    marginTop: hp(1),
  },
  tabText: {
    fontSize: wp(3),
    fontFamily: Typography?.poppins?.Regular,
    marginLeft: wp(2),
  },
  error: {
    maxWidth: wp(43),
    marginTop: hp(0.4),
    marginLeft: wp(0.8),
    color: 'red',
    fontSize: wp(3.3),
    fontFamily: Typography?.poppins?.Regular,
  },
  dropdown: {
    backgroundColor: Colors.primary,
    borderRadius: wp(1.7),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(2),
    marginTop: hp(1.5),
    paddingVertical: hp(0.7),
    width: wp(55),
    borderWidth: wp(0.2),
    borderColor: rgba(Colors.white, 0.4),
  },
  dropdownContainer: {
    backgroundColor: Colors.dullWhite,
    height: hp(30),
    borderRadius: wp(2),
    marginTop: hp(1),
  },
  selected: {
    backgroundColor: Colors.green,
    borderRadius: wp(1),
    color: 'red',
    borderColor: Colors.grey,
  },
  itemTextStyle: {
    fontSize: wp(3.5),
    color: Colors.greyIcn,
    fontFamily: Typography?.poppins?.Regular,
  },
  placeholderStyle: {
    paddingLeft: wp(3),
    fontSize: wp(3.5),
    color: Colors.white,
    fontFamily: Typography?.poppins?.Regular,
  },
  selectedTextStyle: {
    paddingLeft: wp(3),
    fontSize: rfs(13),
    color: Colors.white,
    fontFamily: Typography?.poppins?.Regular,
  },
  icnContainer: {
    backgroundColor: rgba(Colors.dullWhite, 0.15),
    padding: wp(1.5),
    borderRadius: wp(100),
    marginRight: wp(4),
  },
  arrow: {width: wp(3), height: hp(1.5)},
  profileInfoIcn: {
    width: wp(5),
    height: hp(2.5),
  },
  phoneIcn: {
    width: wp(5),
    height: hp(2.2),
  },
  itemImg: {
    width: wp(10),
    height: hp(5),
    borderRadius: wp(1),
    marginTop: hp(0.3),
    marginRight: wp(2),
  },
  itemView: {
    backgroundColor: Colors.dullWhite,
    paddingHorizontal: wp(2),
    paddingVertical: hp(1),
    borderRadius: wp(2),
    marginBottom: hp(2),
  },
  shortIcn: {width: wp(3.6), height: hp(1.8), marginLeft: wp(3)},
  blueEye: {width: wp(3.9), height: hp(1.9), marginLeft: wp(2)},
  userImg: {width: wp(8.5), height: wp(8.5), borderRadius: wp(100)},
  blueDot: {
    backgroundColor: Colors.primary,
    paddingHorizontal: wp(0.5),
    paddingVertical: wp(0.5),
    borderRadius: wp(100),
    marginHorizontal: wp(1),
  },
  userName: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3),
  },
  date: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Light,
    fontSize: wp(3),
  },
  time: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Light,
    fontSize: wp(3),
  },
  separator: {
    backgroundColor: '#EBEBEB',
    height: hp(0.1),
    width: wp(90),
    alignSelf: 'center',
    marginVertical: hp(2),
  },
  itemDetailContainer: {marginLeft: wp(3)},
  userDetailContainer: {marginLeft: wp(1.8)},
  userContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  infoContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  docInfoContainer: {
    alignItems: 'center',
    marginLeft: wp(2),
  },
  vehicleInfoContainer: {
    marginRight: wp(6),
  },
  center: {
    alignItems: 'center',
  },
  name: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.SemiBold,
    fontSize: wp(3.8),
    maxWidth: wp(50),
  },
  dataContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  subName: {
    color: Colors.greyIcn,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.1),
  },
  value: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(2.7),
    marginLeft: wp(1),
  },
  simpleValue: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(2.7),
  },
  lastItemContainer: {
    alignItems: 'flex-end',
    flex: 1,
  },
  label: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Light,
    fontSize: wp(2.7),
    marginLeft: wp(1),
  },
  simpleLabel: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Light,
    fontSize: wp(2.7),
  },
  plusOptionsContainer: {
    position: 'absolute',
    backgroundColor: 'white',
    alignItems: 'center',
    paddingHorizontal: wp(3),
    paddingTop: hp(2),
    borderTopLeftRadius: wp(4),
    borderTopRightRadius: wp(4),
    borderBottomLeftRadius: wp(4),
    marginRight: wp(3),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 11,
    },
    shadowOpacity: 0.57,
    shadowRadius: 15.19,
    elevation: 24,
  },
  optionBackground: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(3),
    paddingVertical: hp(0.6),
    width: wp(40),
    borderRadius: wp(2),
    marginBottom: hp(2),
  },
  optionMenuName: {
    color: Colors.black,
    fontSize: wp(3.5),
    fontFamily: Typography?.poppins?.Regular,
  },
  forwardIcn: {width: wp(3.5), height: hp(2), marginLeft: wp(3)},
  optionMainContainer: {
    alignItems: 'flex-end',
    zIndex: 1000,
    position: 'relative',
  },
  modalHeading: {
    marginTop: hp(1),
    color: Colors.black,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(4),
  },
  confirmationText: {
    color: Colors.greyIcn,
    textAlign: 'center',
    alignSelf: 'center',
    width: wp(60),
    marginTop: hp(0.6),
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.3),
  },
  submitText: {
    color: Colors.black,
    fontSize: wp(3.8),
    fontFamily: Typography?.poppins?.Medium,
  },
  cancelContainer: {
    paddingHorizontal: wp(10),
    paddingVertical: hp(1),
    borderRadius: wp(2),
    borderWidth: wp(0.2),
    borderColor: Colors.primary,
  },
  deleteContainer: {
    paddingHorizontal: wp(10),
    paddingVertical: hp(1),
    borderRadius: wp(2),
    borderWidth: wp(0.2),
    backgroundColor: Colors.primary,
    marginLeft: wp(3),
  },
  setVehicleContainer: {
    paddingHorizontal: wp(5),
    paddingVertical: hp(1),
    borderRadius: wp(2),
    borderWidth: wp(0.2),
    backgroundColor: Colors.primary,
    marginLeft: wp(3),
  },
  clearText: {
    width: wp(30),
    paddingVertical: hp(0.9),
    borderRadius: wp(2),
  },
  clearButtonText: {
    color: Colors.white,
    fontSize: wp(3.8),
    fontFamily: Typography?.poppins?.Medium,
  },
  setText: {
    color: Colors.white,
    fontSize: wp(3.2),
    fontFamily: Typography?.poppins?.Medium,
  },
  filterButtonsContainer: {
    flexDirection: 'row',
    marginTop: hp(2.5),
  },
  button: {marginTop: hp(3)},
  heading: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(4.4),
    marginBottom: hp(2),
  },
  tabSubContainer: {
    backgroundColor: Colors.dullWhite,
    width: wp(45),
    alignItems: 'center',
    paddingVertical: hp(1),
    borderRadius: wp(2.3),
  },
  blueTabContainer: {
    backgroundColor: Colors.primary,
    width: wp(45),
    alignItems: 'center',
    paddingVertical: hp(1),
    borderRadius: wp(2.3),
  },
  activityIndicator: {
    marginTop: '45%',
    alignSelf: 'center',
  },
  fab: {
    position: 'absolute',
    right: wp(6),
    bottom: hp(5),
    backgroundColor: Colors.primary,
    borderRadius: 30,
    width: wp(15),
    height: wp(15),
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    zIndex: 100,
  },
  fabIcon: {
    width: wp(7),
    height: wp(7),
    tintColor: '#fff',
    marginRight: wp(0.7),
  },
  fabIconss: {
    width: wp(7),
    height: wp(7),
    tintColor: '#fff',
    marginRight: wp(0.7),
  },
  noDataAvailable: {
    color: Colors.black,
    fontSize: wp(4),
    alignSelf: 'center',
    fontFamily: Typography?.poppins?.Medium,
  },
  bottomIcn: {
    width: wp(8),
    height: hp(3.5),
  },
  carImg: {
    width: wp(18),
    height: hp(7),
    borderRadius: wp(2)
  },
  carInfoContainer: {
    marginLeft: hp(1.5),
    flexDirection: 'column',
    flexWrap: 'wrap',
  },
});
