import {StyleSheet} from 'react-native';
import {Colors, rgba} from '../../Theme/Colors';
import {hp, wp} from '../../Theme/Responsiveness';
import Typography from '../../Theme/Typography';

export const styles = StyleSheet.create({
  mainView: {
    backgroundColor: 'white',
    flex: 1,
    padding:wp(2),
    // paddingVertical:wp(3),
    // paddingHorizontal:wp(3),
  },
  subContainer: {
    paddingHorizontal: wp(3),
  },
  rowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dataContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  centerSpaceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: hp(2),
  },
  userContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  infoContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  docInfoContainer: {
    alignItems: 'center',
    marginLeft: wp(2),
  },
  greyContainer: {
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.6),
    borderRadius: wp(10),
    backgroundColor: Colors.dullWhite,
  },
  name: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.7),
    width: wp(60),
  },
  description: {
    color: Colors.greyIcn,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.3),
    width: wp(60),
  },
  uplaod: {
    color: Colors.greyIcn,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.6),
  },
  blueContainer: {
    backgroundColor: Colors.primary,
    width: wp(7),
    height: wp(7),
    borderRadius: wp(100),
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: wp(2),
  },
  backIcn: {width: wp(4.4), height: hp(2.2)},
  recent: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(4.7),
  },
  uploadIcn: {width: wp(3), height: hp(1.5)},
  itemImg: {
    width: wp(10),
    height: hp(5),
    borderRadius: wp(1),
    marginTop: hp(0.3),
  },
  itemView: {
    backgroundColor: Colors.dullWhite,
    paddingHorizontal: wp(2),
    paddingVertical: hp(1),
    borderRadius: wp(2),
    marginBottom: hp(2),
  },
  shortIcn: {width: wp(4.5), height: wp(4.5), marginLeft: wp(2)},
  userImg: {width: wp(10), height: wp(10), borderRadius: wp(100)},
  blueDot: {
    backgroundColor: Colors.primary,
    paddingHorizontal: wp(0.7),
    paddingVertical: wp(0.7),
    borderRadius: wp(100),
    marginHorizontal: wp(1),
  },
  userName: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(3.5),
  },
  date: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Light,
    fontSize: wp(3.5),
  },
  time: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Light,
    fontSize: wp(3),
  },
  separator: {
    backgroundColor: '#EBEBEB',
    height: hp(0.1),
    width: wp(90),
    alignSelf: 'center',
    marginVertical: hp(2),
  },
  detailContainer: {marginLeft: wp(3)},
  userDetailContainer: {marginLeft: wp(1)},
  noDataAvailable: {
    color: Colors.black,
    fontSize: wp(4),
    alignSelf: 'center',
    fontFamily: Typography?.poppins?.Medium,
  },
  activityIndicator: {
    position: 'absolute',
    alignSelf: 'center',
    top: hp(40),
  },
  crossContainer: {position: 'absolute', top: hp(1), right: wp(2)},
  modalContainer: {
    backgroundColor: 'white',
    paddingHorizontal: wp(5),
    paddingVertical: hp(2),
    borderRadius: wp(3),
  },
  rowSpaceContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  crossIcn: {
    width: wp(5.5),
    height: hp(2.75),
  },
  error: {
    maxWidth: wp(43),
    marginTop: hp(0.4),
    marginLeft: wp(0.8),
    color: 'red',
    fontSize: wp(3.3),
    fontFamily: Typography?.poppins?.Regular,
  },
  placeholderText: {
    color: Colors.black,
    fontSize: wp(3.7),
    fontFamily: Typography?.poppins?.Regular,
    marginTop: hp(1),
    marginBottom: hp(0.5),
  },
  chooseButton: {width: '42%', paddingVertical: hp(1.2)},
  file: {
    color: Colors.black,
    fontSize: wp(3.5),
    fontFamily: Typography?.poppins?.Regular,
    marginLeft: hp(4),
  },
  uploadButton: {width: '100%', marginTop:hp(3)},
  dottedView: {
    borderWidth: 3,
    borderStyle: 'dotted',
    borderColor: '#B0B0B0',
    borderRadius: 8,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 16,
    backgroundColor: '#FAFAFA',
  },
  imgPicker: {
    width: 53,
    height: 40,
    
    marginBottom: 4,
  },
  dropSubText: {
    color: '#888',
    fontSize: 12,
    marginTop: 4,
    fontFamily: 'Poppins-Regular',
  },
  fileNameText: {
    marginLeft: 10,
    marginTop: 8,
    backgroundColor: '#E6EAF3',
    borderRadius: 8,
    color: '#1A237E',
    padding: 8,
    fontSize: 13,
    fontFamily: 'Poppins-Regular',
  },
});
