import {StyleSheet, Platform} from 'react-native';
import {Colors, rgba} from '../../Theme/Colors';
import {hp, rfs, wp} from '../../Theme/Responsiveness';
import Typography from '../../Theme/Typography';

export const styles = StyleSheet.create({
  mainView: {
    backgroundColor: 'white',
    flex: 1,
  },
  subContainer: {
    paddingHorizontal: wp(3),
    flex: 1,
  },
  subHeader: {
    paddingHorizontal: wp(3),
  },
  rowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  vehicleRefContainer: {
    flexDirection: 'row',
    // alignItems: 'center',
    marginTop: hp(1),
  },
  carPropContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(1),
    flexWrap: 'wrap',
  },
  carPropsContainer: {
    backgroundColor: rgba(Colors.white, 0.12),
    width:'100%',
    
    borderRadius: wp(2),
    paddingHorizontal: wp(3),
    paddingBottom: hp(1),
  },
  priceTxt: {
    color: 'white',
    fontSize: wp(3.5),
    fontFamily: Typography?.poppins?.Regular,
    maxWidth:wp(18),
  },
  carName: {
    color: Colors.black,
    fontSize: wp(3.7),
    fontFamily: Typography?.poppins?.SemiBold,
  },
  whiteCarName: {
    color: 'white',
    fontSize: wp(3.7),
    fontFamily: Typography?.poppins?.SemiBold,
    maxWidth:wp(38),
  },
  optionName: {
    color: Colors.black,
    fontSize: wp(3.5),
    fontFamily: Typography?.poppins?.Regular,
    width: wp(30),
  },
  itemOptionName: {
    color: Colors.black,
    fontSize: wp(3.5),
    fontFamily: Typography?.poppins?.Regular,
    width: wp(20),
  },
  itemContainer: {
    backgroundColor: Colors.dullWhite,
    paddingHorizontal: wp(2),
    paddingVertical: hp(1.5),
    borderRadius: wp(3),
    marginBottom: hp(2),
  },
  greyContainer: {
    backgroundColor: Colors.dullWhite,
padding:wp(2),
    borderRadius: wp(3),
    marginVertical: hp(2),
  },
  placeholderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: wp(3),
  },
  tabSubContainer: {
    backgroundColor: Colors.dullWhite,
    paddingHorizontal: wp(10),
    paddingVertical: hp(1),
    borderRadius: wp(2.3),
  },
  blueTabContainer: {
    backgroundColor: Colors.primary,
    paddingHorizontal: wp(10),
    paddingVertical: hp(1),
    borderRadius: wp(2.3),
  },
  modalContainer: {
    backgroundColor: 'white',
    paddingHorizontal: wp(5),
    paddingVertical: hp(2),
    borderRadius: wp(3),
  },
  rowSpaceContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  itemOptionSpaceContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 1,
  },
  tabContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginTop: hp(1),
  },
  optionSpaceContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: hp(0.5),
  },
  plusOptionContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    backgroundColor: Colors.dullWhite,
    borderRadius: wp(2),
    paddingVertical: hp(1),
    paddingHorizontal: wp(3),
    marginBottom: hp(0.5),
  },
  searchContainer: {
    marginTop: hp(2.5),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 2,
  },
  centerSpaceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  subHeaderContainer: {
    marginVertical: hp(2.5),
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  iconStyle: {
    width: wp(12),
    height: hp(6),
  },
  backIcn: {
    width: wp(4),
    height: hp(2),
  },
  carImg: {
    width: wp(20),
    height: hp(9),
    borderRadius:wp(2)
  },
  listForwardIcn: {
    width: wp(3),
    height: hp(1.5),
    marginLeft: wp(1),
  },
  crossIcn: {
    width: wp(5.5),
    height: hp(2.75),
  },
  optionIcn: {
    width: wp(5.5),
    height: hp(3),
    marginTop: hp(0.2),
  },

  deleteIcn: {
    width: wp(5),
    height: hp(2.5),
  },
  priceContainer: {
    backgroundColor: rgba(Colors.white, 0.12),
    paddingHorizontal: wp(4),
    paddingVertical: hp(0.65),
    borderRadius: wp(5),
  },
  primaryPriceContainer: {
    backgroundColor: Colors.primary,
    paddingHorizontal: wp(4),
    paddingVertical: hp(0.65),
    borderRadius: wp(5),
  },
  negativeIndex:{
    position:'relative',
    zIndex:-1
  },
  carInfoContainer: {
    marginLeft: hp(1.5),
  },
  description: {
    color: Colors.greyIcn,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.1),
  },
  whiteDescription: {
    color: rgba(Colors.white, 0.6),
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.1),
    maxWidth:wp(45),
  },
  detailText: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.3),
  },
  viewText: {
    color: Colors.primary,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(3.3),
    alignSelf: 'center',
  },
  titleText: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(5),
  },
  modelText: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.SemiBold,
    fontSize: wp(5),
  },
  whiteDetailText: {
    color: 'white',
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.5),
  },
  detailContainer: {
    marginTop: hp(0.5),
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  crossContainer: {position: 'absolute', top: hp(1), right: wp(2)},
  optionText: {
    color: Colors.greyIcn,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3),
    marginRight: wp(1.5),
    marginTop: hp(0.4),
  },
  carOptionText: {
    color: Colors.white,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3),
    marginRight: wp(1.5),
    marginTop: hp(0.4),
  },
  carValueText: {
    color: Colors.white,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(3),
  },
  valueText: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(3),
  },
  descriptionText: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(3),
  },
  optionContainer: {
    position: 'absolute',
    zIndex: 1000,
    backgroundColor: 'white',
    paddingHorizontal: wp(2),
    paddingVertical: hp(1),
    borderRadius: wp(2),
    top: hp(3),
    right: wp(3),
  },
  plusOptionsContainer: {
    backgroundColor: 'white',
    position: 'absolute',
    zIndex: 123,
    right: wp(10),
    alignItems: 'center',
    paddingHorizontal: wp(3),
    paddingTop: hp(2),
    paddingVertical: hp(3),
    borderTopLeftRadius: wp(3),
    borderTopRightRadius: wp(3),
    borderBottomLeftRadius: wp(3),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 11,
    },
    shadowOpacity: 0.57,
    shadowRadius: 15.19,
    elevation: 24,
  },
  forwardIcn: {width: wp(3.5), height: hp(2), marginLeft: wp(14)},
  chainIcn: {width: wp(5), height: hp(2.5), marginLeft: wp(14)},
  nextIcn: {width: wp(2.6), height: hp(1.3), marginLeft: wp(1)},
  header: {backgroundColor: Colors.primary, paddingBottom: hp(2)},
  placeholderText: {
    color: Colors.primary,
    fontSize: wp(3.5),
    fontFamily: Typography?.poppins?.Medium,
    marginBottom: hp(1),
  },
  blackPlaceholderText: {
    color: Colors.black,
    fontSize: wp(3.5),
    fontFamily: Typography?.poppins?.Regular,
    marginLeft: wp(1),
    marginRight: wp(3),
  },
  tabText: {
    fontSize: wp(3.5),
    fontFamily: Typography?.poppins?.Regular,
    marginLeft: wp(2),
  },
  error: {
    maxWidth: wp(35),
    marginTop: hp(0.4),
    marginLeft: wp(0.8),
    color: 'red',
    fontSize: wp(3.3),
    fontFamily: Typography?.poppins?.Regular,
  },
  dropdown: {
    backgroundColor: Colors.dullWhite,
    borderRadius: wp(2),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.9),
   
    borderWidth: wp(0.3),
    borderColor: Colors.primary,
  },
  dropdownContainer: {
    backgroundColor: Colors.dullWhite,
    width:wp(40),
    height: hp(15),
    fontSize:rfs(15),
    borderRadius: wp(2),
    marginTop: hp(1),
  },
  selected: {
    backgroundColor: Colors.green,
    borderRadius: wp(1),
    color: 'red',
    borderColor: Colors.grey,
  },
  itemTextStyle: {
    fontSize: wp(3.5),
    color: Colors.greyIcn,
    fontFamily: Typography?.poppins?.Regular,
  },
  placeholderStyle: {
    paddingLeft: wp(3),
    fontSize: wp(3.5),
    color: Colors.greyIcn,
    fontFamily: Typography?.poppins?.Regular,
  },
  selectedTextStyle: {
    backgroundColor: Colors.dullWhite,
    paddingLeft: wp(3),
    fontSize: rfs(13),
    color: Colors.black,
    fontFamily: Typography?.poppins?.Regular,
  },
  arrow: {width: wp(4.4), height: hp(2.2)},
  blueDot: {
    backgroundColor: Colors.primary,
    paddingHorizontal: wp(0.8),
    paddingVertical: wp(0.8),
    borderRadius: wp(100),
  },
  outerCircle: {
    borderColor: Colors.primary,
    borderWidth: wp(0.2),
    width: wp(3),
    height: wp(3),
    borderRadius: wp(100),
    alignItems: 'center',
    justifyContent: 'center',
  },
  date: {
    color: Colors.greyIcn,
    fontSize: wp(3),
    fontFamily: Typography?.poppins?.Regular,
  },
  startRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  repairContainer: {
    backgroundColor: rgba('#C9C9C9', 0.5),
    paddingHorizontal: wp(5),
    paddingVertical: hp(0.65),
    borderRadius: wp(5),
  },
  repairText: {
    color: Colors.greyIcn,
    fontSize: wp(3.4),
    fontFamily: Typography?.poppins?.Regular,
  },
  bottomButtonContainer: {
    paddingHorizontal: wp(3),
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    marginBottom: hp(2),
    marginTop: hp(1),
  },
  bottomButton: {
    width: wp(30),
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: hp(1.8),
    marginRight: wp(3),
    borderColor: Colors.black,
    borderRadius: wp(3),
    borderWidth: wp(0.3),
  },
  bottomContainer: {
    position: 'absolute',
    width: '100%',
    bottom: 0,
    backgroundColor: Colors.white,
    paddingBottom: Platform.OS === 'ios' ? 0 : 0,
    zIndex: 1000,
  },
  bottomPrimaryButton: {
    width: wp(30),
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: hp(2),
    backgroundColor: Colors.primary,
    borderRadius: wp(3),
  },
  buttonText: {
    color: Colors.black,
    fontSize: wp(4),
    fontFamily: Typography?.poppins?.Regular,
  },
  buttonPrimaryText: {
    color: Colors.white,
    fontSize: wp(4),
    fontFamily: Typography?.poppins?.Regular,
  },
  plusIcn: {
    position: 'absolute',
    bottom: hp(5),
    right: wp(3),
    alignItems: 'flex-end',
  },
  plus: {width: wp(17), height: hp(8.5)},
  barCodeImg: {width: wp(80), height: hp(10), alignSelf: 'center'},
  qrCodeImg: {
    width: wp(80),
    height: hp(20),
    alignSelf: 'center',
    marginVertical: hp(2),
  },
  button: {marginTop: hp(1), width: wp(80)},
  memoText: {
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.3),
    color: Colors.greyIcn,
  },
  option: {
    backgroundColor: Colors.dullWhite,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: wp(1.9),
    paddingVertical: hp(0.6),
    borderRadius: wp(2),
    width: '106%',
  },
  whiteOption: {
    backgroundColor: Colors.white,
    flexDirection: 'row',
    marginTop: hp(1),
  },
  upIcn: {width: wp(4.5), height: hp(2), marginLeft: wp(14)},
  activityIndicator: {
    alignSelf: 'center',
    marginTop: hp(3),
  },
  noDataAvailable: {
    color: Colors.black,
    fontSize: wp(4),
    alignSelf: 'center',
    fontFamily: Typography?.poppins?.Medium,
  },
  placeholderGreyContainer: {
    backgroundColor: Colors.dullWhite,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingVertical: hp(10),
    borderRadius: wp(3),
  },
  emptyGreyContainer: {
    backgroundColor: Colors.dullWhite,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop:hp(1),
    position:'relative',
    zIndex:1,
    width: '100%',
    paddingVertical: hp(3.5),
    borderRadius: wp(3),
  },
  noRecordText: {
    color: Colors.black,
    fontSize: wp(3.8),
    fontFamily: Typography?.poppins?.SemiBold,
  },
  noRecordInfoText: {
    color: Colors.black,
    fontSize: wp(3.2),
    fontFamily: Typography?.poppins?.Regular,
  },
  noRecordInfoBoldText: {
    color: Colors.black,
    fontSize: wp(3.2),
    fontFamily: Typography?.poppins?.SemiBold,
  },
  squarePlus: {
    width: wp(9),
    height: hp(4.4),
  },
  flexEnd: {alignItems: 'flex-end'},
  content:{flexGrow: 1, paddingBottom: hp(20)},
  list:{marginTop: hp(3)},
  tabletItemContainer: {
    marginBottom: hp(4),
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.5),
    borderRadius: wp(3),
    marginHorizontal: wp(3),

  },
});
