export const icn = {
  world: require('./Icons/world.png'),
  logo: require('./Icons/logo.png'),
  user: require('./Icons/user.png'),
  eye: require('./Icons/eye.png'),
  home: require('./Icons/home.png'),
  car: require('./Icons/car.png'),
  crm: require('./Icons/crm.png'),
  profile: require('./Icons/profile.png'),
  drawer: require('./Icons/drawer.png'),
  message: require('./Icons/message.png'),
  setting: require('./Icons/setting.png'),
  search: require('./Icons/search.png'),
  infoInventory: require('./Icons/infoInventory.png'),
  infoCrm: require('./Icons/infoCrm.png'),
  back: require('./Icons/back.png'),
  newChat: require('./Icons/newChat.png'),
  sampleUser: require('./Icons/userSample.png'),
  edit: require('./Icons/edit.png'),
  next: require('./Icons/next.png'),
  key: require('./Icons/key.png'),
  logout: require('./Icons/logout.png'),
  pen: require('./Icons/pen.png'),
  mic: require('./Icons/mic.png'),
  send: require('./Icons/send.png'),
  separator: require('./Icons/seperator.png'),
  clipper:require('./Icons/clipper.png'),
  greenCircle:require('./Icons/greenCircle.png'),
  videoCall:require('./Icons/videoCall.png'),
  phoneCall:require('./Icons/phoneCall.png'),
  list:require('./Icons/list.png'),
  squares:require('./Icons/squares.png'),
  acura:require('./Icons/acura.png'),
  alpha:require('./Icons/alpha.png'),
  forward:require('./Icons/forward.png'),
  filter:require('./Icons/filter.png'),
  inventoryCar:require('./Icons/inventoryCar.png'),
  tick:require('./Icons/tick.png'),
  optionDots:require('./Icons/optionDots.png'),
  upperArrow:require('./Icons/upperArrow.png'),
  star:require('./Icons/star.png'),
  share:require('./Icons/share.png'),
  carEye:require('./Icons/carEye.png'),
  carCheck:require('./Icons/carCheck.png'),
  man:require('./Icons/man.png'),
  smallCar:require('./Icons/smallCar.png'),
  cross:require('./Icons/cross.png'),
  vehicle:require('./Icons/vehicle.png'),
  vehicleCar:require('./Icons/vehicleCar.png'),
  copy:require('./Icons/copy.png'),
  info:require('./Icons/info.png'),
  mile:require('./Icons/mile.png'),
  pumpStation:require('./Icons/pumpStation.png'),
  loc:require('./Icons/loc.png'),
  carKeta:require('./Icons/carKeta.png'),
  upload:require('./Icons/upload.png'),
  expand:require('./Icons/expand.png'),
  plus:require('./Icons/plus.png'),
  document:require('./Icons/document.png'),
  save:require('./Icons/save.png'),
  download:require('./Icons/download.png'),
  images:require('./Icons/images.png'),
  doc:require('./Icons/doc.png'),
  optionsCar:require('./Icons/optionsCar.png'),
  marketing:require('./Icons/marketing.png'),
  options:require('./Icons/options.png'),
  purchase:require('./Icons/purchase.png'),
  expense:require('./Icons/expense.png'),
  downArrow:require('./Icons/downArrow.png'),
  singlePen:require('./Icons/singlePen.png'),
  barCode:require('./Icons/barCode.png'),
  qrCode:require('./Icons/qrCode.png'),
  whiteRightArrow:require('./Icons/whiteRightArrow.png'),
  dollar:require('./Icons/dollar.png'),
  payment:require('./Icons/payment.png'),
  addPlus:require('./Icons/addPlus.png'),
  delete:require('./Icons/delete.png'),
  chain:require('./Icons/chain.png'),
  longBar:require('./Icons/longBar.png'),
  qr:require('./Icons/qr.png'),
  largeOption:require('./Icons/largeOption.png'),
  upArrow:require('./Icons/upArrow.png'),
  printer:require('./Icons/printer.png'),
  lead:require('./Icons/lead.png'),
  overdueTask:require('./Icons/overdueTask.png'),
  appointment:require('./Icons/appointment.png'),
  showroomLead:require('./Icons/showroomLead.png'),
  email:require('./Icons/email.png'),
  reminder:require('./Icons/reminder.png'),
  filterLines:require('./Icons/filterLines.png'),
  phone:require('./Icons/phone.png'),
  gmail:require('./Icons/gmail.png'),
  scanner:require('./Icons/scanner.png'),
  cam:require('./Icons/cam.png'),
  calender:require('./Icons/calender.png'),
  imageSelect:require('./Icons/imageSelect.png'),
  imageDelete:require('./Icons/imgDelete.png'),
  dummyCar:require('./Icons/dummyCar.png'),
  crmMessengerAll:require('./Icons/crmMessengerAll.png'),
  sms:require('./Icons/sms.png'),
  dummyProfile:require('./Icons/dummyProfile.png'),
  downWhiteArrow:require('./Icons/downWhiteArrow.png'),
  crmProfileMessage:require('./Icons/crmProfileMessage.png'),
  interShare:require('./Icons/interShare.png'),
  card:require('./Icons/card.png'),
  timeline:require('./Icons/timeline.png'),
  notes:require('./Icons/notes.png'), 
  documents:require('./Icons/documents.png'),
  task:require('./Icons/task.png'),
  crmProfile:require('./Icons/crmProfile.png'),
  diagonalDots:require('./Icons/diagonalDots.png'),
  blueFilledEye:require('./Icons/blueFilledEye.png'),
  crmProfileDocument:require('./Icons/crmProfileDocument.png'),
  emailDocument:require('./Icons/emailDocument.png'),
  blueClock:require('./Icons/blueClock.png'),
  documentUpload:require('./Icons/documentUpload.png'),
  heart:require('./Icons/heart.png'),
  creditProfile:require('./Icons/creditProfile.png'),
  creditBalance:require('./Icons/creditBalance.png'),
  employment:require('./Icons/employment.png'),
  address:require('./Icons/address.png'),
  reference:require('./Icons/reference.png'),
  creditReport:require('./Icons/creditReport.png'),
  page:require('./Icons/page.png'),
  success:require('./Icons/success.png'),
  sync:require('./Icons/sync.png'),
  squarePlus:require('./Icons/squarePlus.png'),
  redCross:require('./Icons/redCross.png'),
  focussedUpperArrow:require('./Icons/focusedUpperArrow.png'),
  focussedTick:require('./Icons/focusedTick.png'),
  focussedStar:require('./Icons/focusedStar.png'),
  squareScan:require('./Icons/squareScan.png'),
  videocamera:require('./Icons/video-camera.png'),
};
