import {StyleSheet} from 'react-native';
import {Colors, rgba} from '../../Theme/Colors';
import {hp, wp} from '../../Theme/Responsiveness';
import Typography from '../../Theme/Typography';
import { colors } from 'react-native-keyboard-controller/lib/typescript/components/KeyboardToolbar/colors';

export const styles = StyleSheet.create({
  mainView: {
    backgroundColor: 'white',
    flex: 1,
  },
  subContainer: {
    paddingHorizontal: wp(3),
  },
  rowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backIcn: {width: wp(4.4), height: hp(2.2)},
  centerSpaceContainer: {
    marginTop: hp(2),
    width: wp(90),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  togglecontainer: {
    width: wp(90),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  greyContainer: {
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.6),
    borderRadius: wp(10),
    backgroundColor: Colors.dullWhite,
  },
  manage: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.1),
  },
  uplaod: {
    color: Colors.greyIcn,
    fontFamily: Typography?.poppins?.Regular,
    fontSize: wp(3.6),
  },
  recent: {
    color: Colors.black,
    fontFamily: Typography?.poppins?.Medium,
    fontSize: wp(4.7),
  },
  blueContainer: {
    backgroundColor: Colors.primary,
    width: wp(7),
    height: wp(7),
    borderRadius: wp(100),
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: wp(2),
  },
  whiteContainer: {
    backgroundColor: 'white',
    width: wp(6),
    height: wp(6),
    borderRadius: wp(100),
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadIcn: {width: wp(3), height: hp(1.5)},
  itemImg: {
    width: wp(90),
    height: hp(30),
    borderRadius: wp(4),
    marginBottom: hp(2),
    resizeMode: 'cover'
  },
  noDataAvailable: {
    color: Colors.black,
    fontSize: wp(4),
    alignSelf: 'center',
    fontFamily: Typography?.poppins?.Medium,
  },
  activityIndicator: {
    position: 'absolute',
    alignSelf: 'center',
    top: hp(40),
  },
  modal: {
    margin: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '100%',
    height: '100%',
    borderRadius: wp(3),
    overflow: 'hidden',
  },
  closeButton: {
    position: 'absolute',
    right: wp(3),
    top: hp(1),
    zIndex: 1,
  },
  fullImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    
  },
  crossIcn: {
    width: wp(8),
    height: hp(4),
  },
  delete: {
    width: wp(4),
    height: wp(2),
    marginRight: wp(2),
  },
  absoluteContainer: {
    position: 'absolute',
    top: hp(1),
    right: wp(2),
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  uploadSection: {
    marginTop: hp(2),
    paddingHorizontal: wp(4),
  },
  uploadButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: wp(2),
  },
  uploadButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  uploadButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryButton: {
    backgroundColor: Colors.primary,
    elevation: 4,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  secondaryButton: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.primary,
    elevation: 2,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  iconContainer: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(5),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  uploadIcon: {
    width: wp(4),
    height: wp(4),
  },
  uploadText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
  },
  uploadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: wp(2),
  },
  imageContainer: {
    position: 'relative',
    marginBottom: hp(2),
  },
  checkboxContainer: {
    marginRight: 6,
    position: 'relative',
    zIndex: 2,
  },
  checkbox: {
    width: wp(5),
    height: wp(5),
    borderRadius: wp(1),
    borderWidth: 1,
    borderColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: Colors.primary,
  },
  checkboxInner: {
    width: wp(3),
    height: wp(3),
    borderRadius: wp(0.5),
    backgroundColor: Colors.white,
  },
  deleteButton: {
    marginLeft: 6,
  },
  checkboxLabel: {
    fontSize: 13,
    color: Colors.primary,
    marginTop:wp(1),
    fontFamily: Typography?.poppins?.Medium,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(1),
    paddingHorizontal: wp(4),
    borderRadius: wp(2),
    minWidth: wp(20),
    gap: wp(1.5),
  },
  uploadModernButton: {
    backgroundColor: Colors.primary,
    elevation: 2,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  applyRemoveModernButton: {
    backgroundColor: Colors.dullWhite,
    borderWidth: 1,
    borderColor: Colors.primary,
    elevation: 1,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
  },
  actionIcon: {
    width: wp(5),
    height: wp(5),
    tintColor: Colors.primary,
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: Typography?.poppins?.Medium,
    color: Colors.white,
  },
  applyModernButton: {
    backgroundColor: Colors.primary,
    elevation: 2,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  removeModernButton: {
    backgroundColor: Colors.dullWhite,
    borderWidth: 1,
    borderColor: Colors.primary,
    elevation: 1,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
  },
  removeButtonText: {
    fontSize: 12,
    fontWeight: '600',
    fontFamily: Typography?.poppins?.Medium,
    color: Colors.primary,
  },
  textButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: wp(2),
    borderWidth:1,
    borderBlockColor:Colors.darkGrey,
    borderRadius:10,
    backgroundColor:Colors.dullWhite,
    // gap: wp(1),
  },
  textButton: {
    paddingHorizontal: wp(1),
    paddingVertical: hp(0.5),
  },
  textButtonText: {
    color: Colors.primary,
    fontSize: 14,
    fontWeight: '500',
    fontFamily: Typography?.poppins?.Medium,
  },
  verticalDivider: {
    width: 1,
    height: 24,
    backgroundColor: Colors.greyLine,
    marginHorizontal: wp(1),
  },
  toggleButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: hp(1),
  },
  toggleButton: {
    paddingHorizontal: wp(6),
    paddingVertical: hp(1),
    borderRadius: wp(2),
    borderWidth: 1,
    borderColor: Colors.primary,
  },
  toggleButtonActive: {
    backgroundColor: Colors.primary,
  },
  toggleButtonInactive: {
    backgroundColor: Colors.dullWhite,
  },
  toggleButtonText: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: Typography?.poppins?.Medium,
  },
  fab: {
    position: 'absolute',
    bottom: hp(6),
    right: wp(6),
    width: wp(14),
    height: wp(14),
    borderRadius: wp(7),
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    zIndex: 100,
  },
  fabIcon: {
    width: wp(7),
    height: wp(7),
    tintColor: '#fff',
    marginRight:wp(1),
  },
  simpleCheckboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  simpleCheckbox: {
    width: wp(5),
    height: wp(5),
    borderWidth: 2,
    borderColor: Colors.primary,
    backgroundColor: '#fff',
    marginRight: wp(2),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: wp(1),
  },
  simpleCheckboxChecked: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  simpleCheckboxInner: {
    width: wp(3),
    height: wp(3),
    backgroundColor: '#fff',
    borderRadius: wp(0.5),
  },
  bottomModal: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  selectAllModalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: wp(5),
    borderTopRightRadius: wp(5),
    padding: wp(5),
    minHeight: hp(30),
  },
  selectAllTabsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp(2),
  },
  selectAllTab: {
    flex: 1,
    paddingVertical: hp(1.2),
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  selectAllTabActive: {
    borderBottomColor: Colors.primary,
  },
  selectAllTabText: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: '500',
    opacity: 0.6,
  },
  selectAllTabTextActive: {
    opacity: 1,
    fontWeight: '700',
  },
  selectAllButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: hp(2),
    gap: wp(4),
  },
  selectAllActionButton: {
    flex: 1,
    paddingVertical: hp(1.5),
    borderRadius: wp(2),
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: wp(1),
  },
  selectAllActionText: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: Typography?.poppins?.Medium,
  },
  selectedImagesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: hp(2),
    gap: wp(2),
  },
  selectedImage: {
    width: wp(90),
    height: hp(30),
    borderRadius: wp(2),
    marginBottom: hp(1),
    backgroundColor: '#eee',
  },
  menuBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
    zIndex: 999,
  },
  menuButton: {
    padding: wp(2),
    marginLeft: wp(2),
    zIndex: 1000,
  },
  menuIcon: {
    width: wp(5),
    height: wp(5),
    tintColor: Colors.primary,
  },
  menuContainer: {
    position: 'absolute',
    backgroundColor: 'white',
    borderRadius: wp(2),
    padding: wp(2),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    zIndex: 1000,
    minWidth: wp(40),
    right: wp(4),
  },
  menuItem: {
    paddingVertical: hp(1.2),
    paddingHorizontal: wp(3),
    borderBottomWidth: 1,
    borderBottomColor: Colors.greyLine,
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuItemLast: {
    borderBottomWidth: 0,
  },
  menuText: {
    color: Colors.primary,
    fontSize: 14,
    fontFamily: Typography?.poppins?.Medium,
    marginLeft: wp(2),
  },
  menuItemIcon: {
    width: wp(4),
    height: wp(4),
    tintColor: Colors.primary,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: hp(50),
  },
  listContainer: {
    paddingBottom: hp(13),
  },
  emptyListContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp(1),
    marginBottom: hp(1),
    gap: wp(4),
    backgroundColor: Colors.white,
    width: '100%',
  },
  previewButton: {
    marginHorizontal: 6,
  },
  previewIcon: {
    width: wp(5),
    height: wp(5),
    tintColor: Colors.primary,
  },
  gridItem: {
    flex: 1,
    margin: 4,
    aspectRatio: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    overflow: 'hidden',
  },
  selectAllContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: hp(2),
    paddingHorizontal: wp(1),
  },
  imageBox: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gridImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  arrowButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 2,
  },
  arrowIcon: {
    width: 18,
    height: 18,
    tintColor: '#222',
  },
  gridLabel: {
    marginTop: 8,
    fontSize: 14,
    color: '#222',
    fontWeight: '500',
    textAlign: 'center',
  },
  iconButton: {
    padding: wp(1.5),
    borderRadius: wp(1),
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoContainer: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  playButtonOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  playIcon: {
    width: wp(10),
    height: wp(10),
    tintColor: Colors.white,
  },
  input: {
    borderWidth: 1,
    borderColor: Colors.primary,
    borderRadius: 8,
    width:wp(10),
    marginTop:8,
    height:hp(5.5),
    // padding: 8,
    marginRight: 8,
    fontSize: 14,
    backgroundColor: '#fff',
  },
  videoPreviewContainer: {
    marginTop: 16,
    padding: 6,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    width: '100%',
  },
  previewTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  videoPreview: {
    width: '100%',
    height: 200,
    borderRadius: 8,
    backgroundColor: '#000',
  },

  container: {
    padding: 16,
  },
  // input: {
  //   borderWidth: 1,
  //   borderColor: '#ccc',
  //   paddingHorizontal: 12,
  //   paddingVertical: 10,
  //   borderRadius: 8,
  // },
  // uploadButton: {
  //   backgroundColor: '#007bff',
  //   paddingVertical: 10,
  //   paddingHorizontal: 12,
  //   borderRadius: 8,
  // },
  // uploadButtonText: {
  //   color: '#fff',
  //   fontWeight: 'bold',
  // },
});





